/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.adk.flows.llmflows;

import com.google.adk.agents.ActiveStreamingTool;
import com.google.adk.agents.BaseAgent;
import com.google.adk.agents.CallbackContext;
import com.google.adk.agents.Callbacks.AfterModelCallback;
import com.google.adk.agents.Callbacks.BeforeModelCallback;
import com.google.adk.agents.Callbacks.OnModelErrorCallback;
import com.google.adk.agents.InvocationContext;
import com.google.adk.agents.LiveRequest;
import com.google.adk.agents.LlmAgent;
import com.google.adk.agents.ReadonlyContext;
import com.google.adk.agents.RunConfig.StreamingMode;
import com.google.adk.events.Event;
import com.google.adk.flows.BaseFlow;
import com.google.adk.flows.llmflows.RequestProcessor.RequestProcessingResult;
import com.google.adk.flows.llmflows.ResponseProcessor.ResponseProcessingResult;
import com.google.adk.models.BaseLlm;
import com.google.adk.models.BaseLlmConnection;
import com.google.adk.models.LlmCallsLimitExceededException;
import com.google.adk.models.LlmRegistry;
import com.google.adk.models.LlmRequest;
import com.google.adk.models.LlmResponse;
import com.google.adk.telemetry.Tracing;
import com.google.adk.tools.BaseTool;
import com.google.adk.tools.BaseToolset;
import com.google.adk.tools.ToolContext;
import com.google.common.annotations.VisibleForTesting;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.Iterables;
import com.google.genai.types.FunctionResponse;
import com.google.genai.types.GenerateContentConfig;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.opentelemetry.context.Context;
import io.opentelemetry.context.Scope;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Flowable;
import io.reactivex.rxjava3.core.Maybe;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.disposables.Disposable;
import io.reactivex.rxjava3.observers.DisposableCompletableObserver;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BiFunction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** A basic flow that calls the LLM in a loop until a final response is generated. */
public abstract class BaseLlmFlow implements BaseFlow {
  private static final Logger logger = LoggerFactory.getLogger(BaseLlmFlow.class);

  protected final List<RequestProcessor> requestProcessors;
  protected final List<ResponseProcessor> responseProcessors;

  // Warning: This is local, in-process state that won't be preserved if the runtime is restarted.
  // "Max steps" is experimental and may evolve in the future (e.g., to support persistence).
  protected final int maxSteps;

  public BaseLlmFlow(
      List<RequestProcessor> requestProcessors, List<ResponseProcessor> responseProcessors) {
    this(requestProcessors, responseProcessors, /* maxSteps= */ Optional.empty());
  }

  public BaseLlmFlow(
      List<RequestProcessor> requestProcessors,
      List<ResponseProcessor> responseProcessors,
      Optional<Integer> maxSteps) {
    this.requestProcessors = requestProcessors;
    this.responseProcessors = responseProcessors;
    this.maxSteps = maxSteps.orElse(Integer.MAX_VALUE);
  }

  /**
   * Pre-processes the LLM request before sending it to the LLM. Executes all registered {@link
   * RequestProcessor} transforming the provided {@code llmRequestRef} in-place, and emits the
   * events generated by them.
   */
  private Flowable<Event> preprocess(
      InvocationContext context, AtomicReference<LlmRequest> llmRequestRef) {
    Context currentContext = Context.current();
    LlmAgent agent = (LlmAgent) context.agent();

    Iterable<RequestProcessor> allProcessors =
        Iterables.concat(requestProcessors, ImmutableList.of(getRequestProcessorFromTools(agent)));

    return Flowable.fromIterable(allProcessors)
        .concatMap(
            processor ->
                Single.defer(() -> processor.processRequest(context, llmRequestRef.get()))
                    .compose(Tracing.withContext(currentContext))
                    .doOnSuccess(result -> llmRequestRef.set(result.updatedRequest()))
                    .flattenAsFlowable(
                        result -> result.events() != null ? result.events() : ImmutableList.of()));
  }

  /**
   * Constructs a {@link RequestProcessor} that sequentially applies the {@code processLlmRequest}
   * methods of all tools and toolsets associated with this agent to the incoming {@link
   * LlmRequest}.
   *
   * @return A {@link RequestProcessor} that applies tool-specific modifications to LLM requests.
   */
  @VisibleForTesting
  RequestProcessor getRequestProcessorFromTools(LlmAgent agent) {
    return (context, request) -> {
      ReadonlyContext readonlyContext = new ReadonlyContext(context);
      // Filled as the tools run, so the collision check needs no second pass over the
      // toolsets - that pass cost an extra tools/list request on every model call.
      Set<String> declarationlessConfigNames = new HashSet<>();
      List<BiFunction<LlmRequest.Builder, ToolContext, Completable>> processors = new ArrayList<>();

      for (Object toolOrToolset : agent.toolsUnion()) {
        if (toolOrToolset instanceof BaseTool baseTool) {
          processors.add(
              (builder, ctx) -> applyTool(baseTool, builder, ctx, declarationlessConfigNames));
        } else if (toolOrToolset instanceof BaseToolset baseToolset) {
          // First apply the toolset's own request processor, then unwrap all tools from the toolset
          // and apply each individual tool's request processor sequentially.
          processors.add(
              (builder, ctx) -> {
                Completable c = baseToolset.processLlmRequest(builder, ctx);
                Completable toolsetProcessor = c == null ? Completable.complete() : c;
                return toolsetProcessor
                    .andThen(baseToolset.getTools(readonlyContext))
                    .concatMapCompletable(
                        b -> applyTool(b, builder, ctx, declarationlessConfigNames));
              });
        } else {
          throw new IllegalArgumentException(
              "Object in tools list is not of a supported type: "
                  + toolOrToolset.getClass().getName());
        }
      }

      LlmRequest.Builder builder = request.toBuilder();
      ToolContext toolContext = ToolContext.builder(context).build();
      return Flowable.fromIterable(processors)
          .concatMapCompletable(f -> f.apply(builder, toolContext))
          .andThen(
              Completable.fromAction(
                  () -> {
                    Map<String, BaseTool> declared = builder.build().tools();
                    for (String name : declarationlessConfigNames) {
                      if (declared.containsKey(name)) {
                        throw new IllegalArgumentException("Duplicate tool name: " + name);
                      }
                    }
                  }))
          .andThen(
              Single.fromCallable(
                  () -> RequestProcessingResult.create(builder.build(), ImmutableList.of())));
    };
  }

  /**
   * Runs one tool's request processor, recording the tool's name when it adds an entry to the
   * request's config tools without declaring a function.
   *
   * <p>Those are the in-model built-ins such as {@code google_search}: they never reach {@link
   * LlmRequest#tools()}, so a function tool of the same name sits beside them and the model chooses
   * between two things answering to one name. A declaration-less tool that adds no config entry,
   * such as {@code ExampleTool}, is not one of them and is left alone.
   */
  private static Completable applyTool(
      BaseTool tool,
      LlmRequest.Builder builder,
      ToolContext toolContext,
      Set<String> declarationlessConfigNames) {
    int before = configToolCount(builder);
    Completable result = tool.processLlmRequest(builder, toolContext);
    Completable nonNullResult = result == null ? Completable.complete() : result;
    if (!tool.declaration().isEmpty()) {
      return nonNullResult;
    }
    return nonNullResult.doOnComplete(
        () -> {
          if (configToolCount(builder) > before) {
            declarationlessConfigNames.add(tool.name());
          }
        });
  }

  /** Number of tools currently set on the request's config. */
  private static int configToolCount(LlmRequest.Builder builder) {
    return builder.build().config().flatMap(GenerateContentConfig::tools).map(List::size).orElse(0);
  }

  /**
   * Post-processes the LLM response after receiving it from the LLM. Executes all registered {@link
   * ResponseProcessor} instances. Emits events for the model response and any subsequent function
   * calls.
   */
  protected Flowable<Event> postprocess(
      InvocationContext context,
      Event baseEventForLlmResponse,
      LlmRequest llmRequest,
      LlmResponse llmResponse,
      Context parentContext) {

    List<Iterable<Event>> eventIterables = new ArrayList<>();
    Single<LlmResponse> currentLlmResponse = Single.just(llmResponse);
    for (ResponseProcessor processor : responseProcessors) {
      currentLlmResponse =
          currentLlmResponse
              .flatMap(response -> processor.processResponse(context, response))
              .doOnSuccess(
                  result -> {
                    if (result.events() != null) {
                      eventIterables.add(result.events());
                    }
                  })
              .map(ResponseProcessingResult::updatedResponse);
    }
    return currentLlmResponse.flatMapPublisher(
        updatedResponse ->
            buildPostprocessingEvents(
                    updatedResponse,
                    eventIterables,
                    context,
                    baseEventForLlmResponse,
                    llmRequest,
                    parentContext)
                .compose(Tracing.withContext(parentContext)));
  }

  /**
   * Sends a request to the LLM and returns its response.
   *
   * @param context The invocation context.
   * @param llmRequest The LLM request.
   * @param eventForCallbackUsage An Event object primarily for providing context (like actions) to
   *     callbacks. Callbacks should not rely on its ID if they create their own separate events.
   */
  private Flowable<Event> callLlm(
      Context spanContext,
      InvocationContext context,
      LlmRequest llmRequest,
      Event eventForCallbackUsage) {
    LlmRequest.Builder llmRequestBuilder = llmRequest.toBuilder();

    return Flowable.defer(
        () -> {
          Span span =
              Tracing.getTracer().spanBuilder("call_llm").setParent(spanContext).startSpan();
          Context callLlmContext = spanContext.with(span);

          return Tracing.traceFlowable(
                  callLlmContext,
                  span,
                  () ->
                      handleBeforeModelCallback(context, llmRequestBuilder, eventForCallbackUsage)
                          .toFlowable()
                          .concatMap(
                              llmResp ->
                                  postprocess(
                                          context,
                                          eventForCallbackUsage,
                                          llmRequestBuilder.build(),
                                          llmResp,
                                          callLlmContext)
                                      .doOnSubscribe(
                                          subscription ->
                                              traceCallLlm(
                                                  span,
                                                  context,
                                                  eventForCallbackUsage.id(),
                                                  llmRequestBuilder.build(),
                                                  llmResp)))
                          .switchIfEmpty(
                              Flowable.defer(
                                  () -> {
                                    LlmAgent agent = (LlmAgent) context.agent();
                                    BaseLlm llm =
                                        agent.resolvedModel().model().isPresent()
                                            ? agent.resolvedModel().model().get()
                                            : LlmRegistry.getLlm(
                                                agent.resolvedModel().modelName().get());
                                    LlmRequest finalLlmRequest = llmRequestBuilder.build();

                                    return llm.generateContent(
                                            finalLlmRequest,
                                            context.runConfig().streamingMode()
                                                == StreamingMode.SSE)
                                        .onErrorResumeNext(
                                            exception ->
                                                handleOnModelErrorCallback(
                                                        context,
                                                        llmRequestBuilder,
                                                        eventForCallbackUsage,
                                                        exception)
                                                    .switchIfEmpty(Single.error(exception))
                                                    .toFlowable())
                                        .doOnError(
                                            error -> {
                                              span.setStatus(StatusCode.ERROR, error.getMessage());
                                              span.recordException(error);
                                            })
                                        .concatMap(
                                            llmResp ->
                                                handleAfterModelCallback(
                                                        context, llmResp, eventForCallbackUsage)
                                                    .toFlowable())
                                        .flatMap(
                                            llmResp ->
                                                postprocess(
                                                        context,
                                                        eventForCallbackUsage,
                                                        finalLlmRequest,
                                                        llmResp,
                                                        callLlmContext)
                                                    .doOnSubscribe(
                                                        subscription ->
                                                            traceCallLlm(
                                                                span,
                                                                context,
                                                                eventForCallbackUsage.id(),
                                                                finalLlmRequest,
                                                                llmResp)));
                                  })))
              .compose(Tracing.withContext(spanContext));
        });
  }

  /**
   * Invokes {@link BeforeModelCallback}s. If any returns a response, it's used instead of calling
   * the LLM.
   *
   * @return A {@link Maybe} with the callback result.
   */
  private Maybe<LlmResponse> handleBeforeModelCallback(
      InvocationContext context, LlmRequest.Builder llmRequestBuilder, Event modelResponseEvent) {
    Context currentContext = Context.current();
    Event callbackEvent = modelResponseEvent.toBuilder().build();
    CallbackContext callbackContext =
        new CallbackContext(context, callbackEvent.actions(), callbackEvent.id());

    Maybe<LlmResponse> pluginResult =
        context.pluginManager().beforeModelCallback(callbackContext, llmRequestBuilder);

    LlmAgent agent = (LlmAgent) context.agent();

    List<? extends BeforeModelCallback> callbacks = agent.canonicalBeforeModelCallbacks();
    if (callbacks.isEmpty()) {
      return pluginResult;
    }

    Maybe<LlmResponse> callbackResult =
        Maybe.defer(
            () ->
                Flowable.fromIterable(callbacks)
                    .concatMapMaybe(
                        callback ->
                            callback
                                .call(callbackContext, llmRequestBuilder)
                                .compose(Tracing.withContext(currentContext)))
                    .firstElement());

    return pluginResult.switchIfEmpty(callbackResult);
  }

  /**
   * Invokes {@link OnModelErrorCallback}s when an LLM call fails. If any returns a response, it's
   * used instead of the error.
   *
   * @return A {@link Maybe} with the override {@link LlmResponse}.
   */
  private Maybe<LlmResponse> handleOnModelErrorCallback(
      InvocationContext context,
      LlmRequest.Builder llmRequestBuilder,
      Event modelResponseEvent,
      Throwable throwable) {
    Context currentContext = Context.current();
    Event callbackEvent = modelResponseEvent.toBuilder().build();
    CallbackContext callbackContext =
        new CallbackContext(context, callbackEvent.actions(), callbackEvent.id());
    Exception ex = throwable instanceof Exception e ? e : new Exception(throwable);

    Maybe<LlmResponse> pluginResult =
        context.pluginManager().onModelErrorCallback(callbackContext, llmRequestBuilder, throwable);

    LlmAgent agent = (LlmAgent) context.agent();
    List<? extends OnModelErrorCallback> callbacks = agent.canonicalOnModelErrorCallbacks();

    if (callbacks.isEmpty()) {
      return pluginResult;
    }

    Maybe<LlmResponse> callbackResult =
        Maybe.defer(
            () -> {
              LlmRequest llmRequest = llmRequestBuilder.build();
              return Flowable.fromIterable(callbacks)
                  .concatMapMaybe(
                      callback ->
                          callback
                              .call(callbackContext, llmRequest, ex)
                              .compose(Tracing.withContext(currentContext)))
                  .firstElement();
            });

    return pluginResult.switchIfEmpty(callbackResult);
  }

  /**
   * Invokes {@link AfterModelCallback}s after an LLM response. If any returns a response, it
   * replaces the original.
   *
   * @return A {@link Single} with the final {@link LlmResponse}.
   */
  private Single<LlmResponse> handleAfterModelCallback(
      InvocationContext context, LlmResponse llmResponse, Event modelResponseEvent) {
    Context currentContext = Context.current();
    Event callbackEvent = modelResponseEvent.toBuilder().build();
    CallbackContext callbackContext =
        new CallbackContext(context, callbackEvent.actions(), callbackEvent.id());

    Maybe<LlmResponse> pluginResult =
        context.pluginManager().afterModelCallback(callbackContext, llmResponse);

    LlmAgent agent = (LlmAgent) context.agent();
    List<? extends AfterModelCallback> callbacks = agent.canonicalAfterModelCallbacks();

    if (callbacks.isEmpty()) {
      return pluginResult.defaultIfEmpty(llmResponse);
    }

    Maybe<LlmResponse> callbackResult =
        Maybe.defer(
            () ->
                Flowable.fromIterable(callbacks)
                    .concatMapMaybe(
                        callback ->
                            callback
                                .call(callbackContext, llmResponse)
                                .compose(Tracing.withContext(currentContext)))
                    .firstElement());

    return pluginResult.switchIfEmpty(callbackResult).defaultIfEmpty(llmResponse);
  }

  /**
   * Executes a single iteration of the LLM flow: preprocessing → LLM call → postprocessing.
   *
   * <p>Handles early termination, LLM call limits, and agent transfer if needed.
   *
   * @return A {@link Flowable} of {@link Event} objects from this step.
   * @throws LlmCallsLimitExceededException if the agent exceeds allowed LLM invocations.
   * @throws IllegalStateException if a transfer agent is specified but not found.
   */
  private Flowable<Event> runOneStep(Context spanContext, InvocationContext context) {
    AtomicReference<LlmRequest> llmRequestRef = new AtomicReference<>(LlmRequest.builder().build());

    return Flowable.defer(
        () -> {
          AtomicBoolean preprocessAnswered = new AtomicBoolean(false);
          return preprocess(context, llmRequestRef)
              .doOnNext(
                  event -> {
                    if (!event.functionResponses().isEmpty() && event.finalResponse()) {
                      preprocessAnswered.set(true);
                    }
                  })
              .concatWith(
                  Flowable.defer(
                      () -> {
                        LlmRequest llmRequestAfterPreprocess = llmRequestRef.get();
                        if (context.endInvocation()) {
                          logger.debug("End invocation requested during preprocessing.");
                          return Flowable.empty();
                        }
                        // A tool answered during preprocessing would be replayed below.
                        if (context.isResumable() && preprocessAnswered.get()) {
                          logger.debug("Preprocessing produced a final response; ending the step.");
                          return Flowable.empty();
                        }

                        // As in Python, decide before the model call: the branch may owe work.
                        StepResume.Decision resume =
                            StepResume.decide(context, llmRequestAfterPreprocess.tools());
                        if (resume.action == StepResume.Action.PAUSE) {
                          logger.debug("Pausing the flow: a call is still unanswered.");
                          return Flowable.empty();
                        }
                        if (resume.action == StepResume.Action.REPLAY_CALLS) {
                          logger.debug("Replaying function calls a previous run did not execute.");
                          // Re-id as Python's replay does; PersistBarrier skips an id-less event.
                          return runFunctionCalls(
                                  context,
                                  resume.replayEvent(),
                                  llmRequestAfterPreprocess,
                                  spanContext)
                              .map(event -> event.toBuilder().id(context.newUuid()).build())
                              .concatMap(event -> followTransfer(event, context, spanContext));
                        }

                        try {
                          context.incrementLlmCallsCount();
                        } catch (LlmCallsLimitExceededException e) {
                          logger.error("LLM calls limit exceeded.", e);
                          return Flowable.error(e);
                        }

                        final Event mutableEventTemplate =
                            Event.builder()
                                .id(context.newUuid())
                                .timestamp(context.now().toEpochMilli())
                                .invocationId(context.invocationId())
                                .author(context.agent().name())
                                .branch(context.branch().orElse(null))
                                .build();

                        return callLlm(
                                spanContext,
                                context,
                                llmRequestAfterPreprocess,
                                mutableEventTemplate)
                            .concatMap(
                                event -> {
                                  // Update event ID for the new resulting events
                                  String oldId = event.id();
                                  String newId = context.newUuid();
                                  logger.debug("Resetting event ID from {} to {}", oldId, newId);
                                  event = event.toBuilder().id(newId).build();
                                  return followTransfer(event, context, spanContext);
                                });
                      }));
        });
  }

  /**
   * Executes the full LLM flow by repeatedly calling {@link #runOneStep} until a final response is
   * produced.
   *
   * @return A {@link Flowable} of all {@link Event}s generated during the flow.
   */
  @Override
  public Flowable<Event> run(InvocationContext invocationContext) {
    return run(Context.current(), invocationContext, 0);
  }

  private Flowable<Event> run(
      Context spanContext, InvocationContext invocationContext, int stepsCompleted) {
    Flowable<Event> currentStepEvents = runOneStep(spanContext, invocationContext).cache();
    if (stepsCompleted + 1 >= maxSteps) {
      logger.debug("Ending flow execution because max steps reached.");
      return currentStepEvents;
    }
    @SuppressWarnings("deprecation") // The shim it reports is deprecated by design.
    boolean legacyResumption = invocationContext.isLegacyResumability();

    return currentStepEvents.concatWith(
        currentStepEvents
            .toList()
            .flatMapPublisher(
                eventList -> {
                  if (eventList.isEmpty()
                      || Iterables.getLast(eventList).finalResponse()
                      || Iterables.getLast(eventList).actions().endInvocation().orElse(false)) {
                    logger.debug(
                        "Ending flow execution based on final response, endInvocation action or"
                            + " empty event list.");
                    return Flowable.empty();
                  } else if (legacyResumption && Functions.hasPendingLongRunningCall(eventList)) {
                    // The resumable flow decides before the model call instead, in StepResume.
                    logger.debug("Pausing flow execution on a pending long-running call.");
                    return Flowable.empty();
                  } else {
                    logger.debug("Continuing to next step of the flow.");
                    // Wait until the Runner has persisted this step's events so the next step's
                    // request is not built from a stale session (see PersistBarrier).
                    return PersistBarrier.awaitPersisted(invocationContext, eventList)
                        .andThen(run(spanContext, invocationContext, stepsCompleted + 1));
                  }
                }));
  }

  /**
   * Executes the LLM flow in streaming mode.
   *
   * <p>Handles sending history and live requests to the LLM, receiving responses, processing them,
   * and managing agent transfers.
   *
   * @return A {@link Flowable} of {@link Event}s streamed in real-time.
   */
  @Override
  public Flowable<Event> runLive(InvocationContext invocationContext) {
    AtomicReference<LlmRequest> llmRequestRef = new AtomicReference<>(LlmRequest.builder().build());
    Flowable<Event> preprocessEvents = preprocess(invocationContext, llmRequestRef);
    // Capture agent context at assembly time to use as parent for agent transfer at subscription
    // time. See Flowable.defer() usages below.
    Context spanContext = Context.current();

    return preprocessEvents.concatWith(
        Flowable.defer(
            () -> {
              LlmRequest llmRequestAfterPreprocess = llmRequestRef.get();
              if (invocationContext.endInvocation()) {
                return Flowable.empty();
              }

              String eventIdForSendData = invocationContext.newUuid();
              LlmAgent agent = (LlmAgent) invocationContext.agent();
              BaseLlm llm =
                  agent.resolvedModel().model().isPresent()
                      ? agent.resolvedModel().model().get()
                      : LlmRegistry.getLlm(agent.resolvedModel().modelName().get());
              BaseLlmConnection connection = llm.connect(llmRequestAfterPreprocess);
              Completable historySent =
                  llmRequestAfterPreprocess.contents().isEmpty()
                      ? Completable.complete()
                      : connection
                          .sendHistory(llmRequestAfterPreprocess.contents())
                          .doOnComplete(
                              () ->
                                  Tracing.traceSendData(
                                      Span.current(),
                                      invocationContext,
                                      eventIdForSendData,
                                      llmRequestAfterPreprocess.contents()))
                          .doOnError(
                              error -> {
                                Span span = Span.current();
                                span.setStatus(StatusCode.ERROR, error.getMessage());
                                span.recordException(error);
                                Tracing.traceSendData(
                                    Span.current(),
                                    invocationContext,
                                    eventIdForSendData,
                                    llmRequestAfterPreprocess.contents());
                              })
                          .compose(Tracing.<Event>trace("send_data").setParent(spanContext));

              Flowable<LiveRequest> liveRequests =
                  invocationContext
                      .liveRequestQueue()
                      .get()
                      .get()
                      .doOnNext(
                          request -> {
                            if (!invocationContext.activeStreamingTools().isEmpty()) {
                              for (ActiveStreamingTool activeStreamingTool :
                                  invocationContext.activeStreamingTools().values()) {
                                if (activeStreamingTool.stream() != null) {
                                  activeStreamingTool.stream().send(request);
                                }
                              }
                            }
                          });
              Disposable sendTask =
                  historySent
                      .observeOn(Functions.resolveWorkerScheduler(invocationContext))
                      .andThen(
                          liveRequests
                              .onBackpressureBuffer()
                              .concatMapCompletable(
                                  request -> {
                                    if (request.content().isPresent()) {
                                      return connection.sendContent(request.content().get());
                                    } else if (request.blob().isPresent()) {
                                      return connection.sendRealtime(request.blob().get());
                                    }
                                    return Completable.fromAction(connection::close);
                                  }))
                      .subscribeWith(
                          new DisposableCompletableObserver() {
                            @Override
                            public void onComplete() {
                              connection.close();
                            }

                            @Override
                            public void onError(Throwable e) {
                              connection.close(e);
                            }
                          });

              Event.Builder liveEventBuilderTemplate =
                  Event.builder()
                      .timestamp(invocationContext.now().toEpochMilli())
                      .invocationId(invocationContext.invocationId())
                      .author(invocationContext.agent().name())
                      .branch(invocationContext.branch().orElse(null));

              Span span =
                  Tracing.getTracer().spanBuilder("call_llm").setParent(spanContext).startSpan();
              Context callLlmContext = spanContext.with(span);

              Flowable<Event> receiveFlow =
                  connection
                      .receive()
                      .flatMap(
                          llmResponse -> {
                            Event baseEventForThisLlmResponse =
                                liveEventBuilderTemplate.id(invocationContext.newUuid()).build();
                            return postprocess(
                                invocationContext,
                                baseEventForThisLlmResponse,
                                llmRequestAfterPreprocess,
                                llmResponse,
                                callLlmContext);
                          })
                      .flatMap(
                          event -> {
                            Flowable<Event> events = Flowable.just(event);
                            if (event.actions().transferToAgent().isPresent()) {
                              BaseAgent rootAgent = invocationContext.agent().rootAgent();
                              Optional<BaseAgent> nextAgent =
                                  rootAgent.findAgent(event.actions().transferToAgent().get());
                              if (nextAgent.isEmpty()) {
                                throw new IllegalStateException(
                                    "Agent not found: " + event.actions().transferToAgent().get());
                              }
                              Flowable<Event> nextAgentEvents =
                                  Flowable.defer(
                                      () -> {
                                        try (Scope scope = spanContext.makeCurrent()) {
                                          return nextAgent.get().runLive(invocationContext);
                                        }
                                      });
                              events = Flowable.concat(events, nextAgentEvents);
                            }
                            return events;
                          })
                      .doOnNext(
                          event -> {
                            ImmutableList<FunctionResponse> functionResponses =
                                event.functionResponses();
                            if (!functionResponses.isEmpty()) {
                              invocationContext
                                  .liveRequestQueue()
                                  .get()
                                  .content(event.content().get());
                            }
                            if (event.actions().transferToAgent().isPresent()
                                || event.actions().endInvocation().orElse(false)) {
                              sendTask.dispose();
                              connection.close();
                            }
                          });

              return Tracing.traceFlowable(
                      callLlmContext,
                      span,
                      () ->
                          receiveFlow.takeWhile(
                              event -> !event.actions().endInvocation().orElse(false)))
                  .compose(Tracing.withContext(spanContext));
            }));
  }

  /**
   * Builds an {@link Event} from LLM response, request, and base event data.
   *
   * <p>Populates the event with LLM output and tool function call metadata.
   *
   * @return A fully constructed {@link Event} representing the LLM response.
   */
  private Flowable<Event> buildPostprocessingEvents(
      LlmResponse updatedResponse,
      List<Iterable<Event>> eventIterables,
      InvocationContext context,
      Event baseEventForLlmResponse,
      LlmRequest llmRequest,
      Context parentContext) {
    Flowable<Event> processorEvents = Flowable.fromIterable(Iterables.concat(eventIterables));
    if (updatedResponse.content().isEmpty()
        && updatedResponse.errorCode().isEmpty()
        && !updatedResponse.interrupted().orElse(false)
        && !updatedResponse.turnComplete().orElse(false)
        && (context.runConfig().streamingMode() != StreamingMode.BIDI
            || updatedResponse.usageMetadata().isEmpty())
        && updatedResponse.inputTranscription().isEmpty()
        && updatedResponse.outputTranscription().isEmpty()
        && updatedResponse.groundingMetadata().isEmpty()) {
      return processorEvents;
    }

    Event modelResponseEvent =
        buildModelResponseEvent(context, baseEventForLlmResponse, llmRequest, updatedResponse);
    if (modelResponseEvent.functionCalls().isEmpty()
        || modelResponseEvent.partial().orElse(false)) {
      return processorEvents.concatWith(Flowable.just(modelResponseEvent));
    }

    Flowable<Event> functionEvents =
        runFunctionCalls(context, modelResponseEvent, llmRequest, parentContext);

    return processorEvents.concatWith(Flowable.just(modelResponseEvent)).concatWith(functionEvents);
  }

  /**
   * Emits {@code event}, followed by the transferred-to agent's run when it carries a transfer.
   * Shared so a replayed transfer continues into its target the way a fresh one does.
   */
  private Flowable<Event> followTransfer(
      Event event, InvocationContext context, Context spanContext) {
    Flowable<Event> self = Flowable.just(event);
    if (event.actions().transferToAgent().isEmpty()) {
      return self;
    }
    String agentToTransfer = event.actions().transferToAgent().get();
    Optional<BaseAgent> nextAgent = context.agent().rootAgent().findAgent(agentToTransfer);
    if (nextAgent.isEmpty()) {
      logger.error("Agent not found: {}", agentToTransfer);
      return self.concatWith(
          Flowable.error(new IllegalStateException("Agent not found: " + agentToTransfer)));
    }
    BaseAgent target;
    // Resumable only: restricting the default flow too would move behavior for existing callers.
    if (context.isResumable() && context.agent() instanceof LlmAgent llmAgent) {
      Optional<BaseAgent> declared = declaredTransferTarget(llmAgent, agentToTransfer);
      if (declared.isEmpty()) {
        return self.concatWith(
            Flowable.error(
                new IllegalStateException(
                    "Agent "
                        + llmAgent.name()
                        + " is not allowed to transfer to the requested agent.")));
      }
      target = declared.get();
    } else {
      target = nextAgent.get();
    }
    // Otherwise the target can build its request from a session missing the transfer event.
    return self.concatWith(
        PersistBarrier.awaitPersisted(context, ImmutableList.of(event))
            .andThen(
                // Not around the barrier: andThen subscribes the target on the append's thread.
                Flowable.defer(() -> target.runAsync(context))
                    .compose(Tracing.withContext(spanContext))));
  }

  /**
   * Returns the agent {@code from} may transfer to under {@code name}, or empty when the transfer
   * is not allowed. Resolves through the declared targets rather than the tree, as Python does, so
   * a same-named agent on an unrelated branch cannot stand in for the declared one.
   */
  private static Optional<BaseAgent> declaredTransferTarget(LlmAgent from, String name) {
    if (name.equals(from.name())) {
      return Optional.of(from);
    }
    return AgentTransfer.transferTargets(from).stream()
        .filter(candidate -> candidate.name().equals(name))
        .findFirst();
  }

  /**
   * Runs {@code callEvent}'s function calls and emits what follows from them: the tool-confirmation
   * request, the function response, and any structured final response. Shared by the normal
   * postprocessing path and by replaying calls a previous run never executed.
   */
  private Flowable<Event> runFunctionCalls(
      InvocationContext context, Event callEvent, LlmRequest llmRequest, Context parentContext) {
    try (Scope scope = parentContext.makeCurrent()) {
      Maybe<Event> maybeFunctionResponseEvent =
          context.runConfig().streamingMode() == StreamingMode.BIDI
              ? Functions.handleFunctionCallsLive(context, callEvent, llmRequest.tools())
              : Functions.handleFunctionCalls(context, callEvent, llmRequest.tools());
      return maybeFunctionResponseEvent.flatMapPublisher(
          functionResponseEvent -> {
            Optional<Event> toolConfirmationEvent =
                Functions.generateRequestConfirmationEvent(
                    context, callEvent, functionResponseEvent);
            List<Event> events = new ArrayList<>();
            toolConfirmationEvent.ifPresent(events::add);
            events.add(functionResponseEvent);
            OutputSchema.getStructuredModelResponse(functionResponseEvent)
                .ifPresent(
                    json -> events.add(OutputSchema.createFinalModelResponseEvent(context, json)));
            return Flowable.fromIterable(events);
          });
    }
  }

  /**
   * Traces an LLM call without an associated exception. This is an overload for {@link
   * Tracing#traceCallLlm} for successful calls.
   */
  private void traceCallLlm(
      Span span,
      InvocationContext context,
      String eventId,
      LlmRequest llmRequest,
      LlmResponse llmResponse) {
    Tracing.traceCallLlm(span, context, eventId, llmRequest, llmResponse, null);
  }

  private Event buildModelResponseEvent(
      InvocationContext context,
      Event baseEventForLlmResponse,
      LlmRequest llmRequest,
      LlmResponse llmResponse) {
    Event.Builder eventBuilder =
        baseEventForLlmResponse.toBuilder()
            .timestamp(context.now().toEpochMilli())
            .content(llmResponse.content().orElse(null))
            .partial(llmResponse.partial().orElse(null))
            .errorCode(llmResponse.errorCode().orElse(null))
            .errorMessage(llmResponse.errorMessage().orElse(null))
            .interrupted(llmResponse.interrupted().orElse(null))
            .turnComplete(llmResponse.turnComplete().orElse(null))
            .groundingMetadata(llmResponse.groundingMetadata().orElse(null))
            .avgLogprobs(llmResponse.avgLogprobs().orElse(null))
            .finishReason(llmResponse.finishReason().orElse(null))
            .usageMetadata(llmResponse.usageMetadata().orElse(null))
            .modelVersion(llmResponse.modelVersion().orElse(null))
            .inputTranscription(llmResponse.inputTranscription().orElse(null))
            .outputTranscription(llmResponse.outputTranscription().orElse(null));

    Event event = eventBuilder.build();

    logger.debug("event: {} functionCalls: {}", event, event.functionCalls());

    if (!event.functionCalls().isEmpty()) {
      Functions.populateClientFunctionCallId(event, context.uuidProvider());
      Set<String> longRunningToolIds =
          Functions.getLongRunningFunctionCalls(event.functionCalls(), llmRequest.tools());
      logger.debug("longRunningToolIds: {}", longRunningToolIds);
      if (!longRunningToolIds.isEmpty()) {
        event.setLongRunningToolIds(longRunningToolIds);
      }
    }
    return event;
  }
}
